apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: sbfju6o6i-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-941abb4cb9.ygaf.p3.openshiftapps.com/rhtap/rhtap-qe:4d45ca1b38b0e37a8ad6195d294f8b1d1baacf55@sha256:9b17f723570d50015381b3cf678f483723755425aa7a73229f498be19f986079
        name: container-image  
